FROM node:latest
RUN npm install -g yarn
COPY ./package-docker.json /package.json
COPY ./index.js /index.js
RUN npm install -g bower
COPY ./bower.json /bower.json
RUN bower install --allow-root
RUN yarn
